---
title: "The reticulate package"
subtitle: "Integration of Python into R projects"
output: html_notebook
---

***

### Setup

```{r setup}
library(reticulate)
readr::write_csv(nycflights13::flights, path = "flights.csv")

print(reticulate::py_config())
```

***

# From Python to R


### Use Python to manipulate data

```{python data}
import pandas
flights = pandas.read_csv("flights.csv")
flights = flights[flights['dest'] == "ORD"]
flights = flights[['carrier', 'dep_delay', 'arr_delay']]
flights = flights.dropna()
flights
```

### Use R to visualize Pandas DataFrame

```{r, fig.width=7, fig.height=3}
library(ggplot2)
ggplot(py$flights, aes(carrier, arr_delay)) + geom_point() + geom_jitter()
```

***

# From R to Python

### Use R to read and manipulate data

```{r, message=FALSE}
library(readr)
library(dplyr)
flights <- read_csv("flights.csv") %>%
  filter(dest == "ORD") %>%
  select(carrier, dep_delay, arr_delay) %>%
  na.omit()
```

### Use Python to print R dataframe

```{python print}
print(r.flights.head(10))
```

***

See the [reticulate website](https://rstudio.github.io/reticulate/index.html) for details.
